### ISSUE TITLE
Uploading a large document fails format detection

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/docstore#35]
I just tried to upload a larger-than-usual PDF (69.3MB) into v1.3.2, and got the following error:

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 389, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/usr/local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 125, in asgi
    raise exc from None
  File "/usr/local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 103, in asgi
    await asgi(receive, _send)
  File "/usr/local/lib/python3.6/site-packages/starlette/middleware/gzip.py", line 33, in __call__
    await self.inner(receive, self.send_with_gzip)
  File "/usr/local/lib/python3.6/site-packages/responder/api.py", line 264, in asgi
    req, scope=scope, send=send, receive=receive
  File "/usr/local/lib/python3.6/site-packages/responder/api.py", line 353, in _dispatch_request
    await self._execute_route(route=route, req=req, resp=resp, **options)
  File "/usr/local/lib/python3.6/site-packages/responder/api.py", line 376, in _execute_route
    await r
  File "/usr/local/lib/python3.6/site-packages/responder/background.py", line 42, in __call__
    return await asyncio.ensure_future(func(*args, **kwargs))
  File "api.py", line 184, in upload_document
    await _upload_document_api(req, resp)
  File "api.py", line 156, in _upload_document_api
    doc = index_document(store=store, user_data=prepared_data)
  File "/app/index_helpers.py", line 46, in index_document
    guessed_mimetype = magic.from_buffer(file_data, mime=True)
  File "/usr/local/lib/python3.6/site-packages/magic.py", line 148, in from_buffer
    return m.from_buffer(buffer)
  File "/usr/local/lib/python3.6/site-packages/magic.py", line 82, in from_buffer
    return self._handle509Bug(e)
  File "/usr/local/lib/python3.6/site-packages/magic.py", line 101, in _handle509Bug
    raise e
  File "/usr/local/lib/python3.6/site-packages/magic.py", line 80, in from_buffer
    return maybe_decode(magic_buffer(self.cookie, buf))
  File "/usr/local/lib/python3.6/site-packages/magic.py", line 255, in magic_buffer
    return _magic_buffer(cookie, buf, len(buf))
  File "/usr/local/lib/python3.6/site-packages/magic.py", line 188, in errorcheck_null
    raise MagicException(err)
magic.MagicException: b'cannot allocate 554188544 bytes (Cannot allocate memory)'
```

**Comment by alexwlchan** [comment]
This works now. 👌
